# Generated by Django 2.2 on 2020-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0004_auto_20200528_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='Announcements_text',
            new_name='announcements_text',
        ),
    ]
