# Generated by Django 2.2 on 2020-06-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0006_auto_20200528_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRadioQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tepsite.Program')),
            ],
        ),
    ]
