# Generated by Django 2.2 on 2020-06-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0007_testradioquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testradioquestions',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='testradioquestions',
            name='intern_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
