# Generated by Django 2.2 on 2020-06-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0007_programfeedbackform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans1',
            new_name='Both_the_facility_and_equipment_used_met_all_needs_of_the_course',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans10',
            new_name='I_would_recommend_this_course_to_other_teammates',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans2',
            new_name='Overall_my_impression_of_this_course_was_excellent',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans3',
            new_name='The_amount_of_time_scheduled_for_this_course_was_exactly_what_was_needed_to_meet_the_objectives',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans4',
            new_name='The_course_materials_were_both_useful_and_easy_to_follow',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans5',
            new_name='The_course_objectives_were_clearly_stated_and_used_understandable_terms',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans6',
            new_name='The_instructor_demonstrated_thorough_knowledge_and_understanding_of_the_topic',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans7',
            new_name='The_instructor_presented_information_in_a_clear_understandable_and_professional_manner',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans8',
            new_name='This_course_met_the_defined_objectives',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='ans9',
            new_name='This_course_relates_directly_to_my_current_job_responsibilities',
        ),
    ]
