# Generated by Django 2.2 on 2020-06-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0009_auto_20200621_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='name',
            new_name='intern_name',
        ),
    ]
