# Generated by Django 2.2 on 2020-06-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0010_auto_20200621_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixThinkingHats_SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('I_try_to_formulate_a_clear_definition_of_the_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_the_goal_and_outcome_of_the_problem_I_am_facing', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_plan_to_figure_out_the_most_effective_method_to_proceed_from_the_initial_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_try_to_organize_and_arrange_my_thinking_to_help_move_me_beyond_my_present_circumstances', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_try_to_figure_out_what_I_know_about_the_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_try_to_figure_out_what_I_dont_know_about_the_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_how_I_will_go_about_acquiring_the_facts_stats_and_data_that_will_help_me_resolve_this_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_figure_out_potential_solutions_exist_based_on_the_facts_stats_and_data_I_have_collected', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_consider_what_my_feelings_tell_me_about_the_choice_I_am_about_to_make', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_better_ways_to_solve_a_problem_based_on_my_feelings', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_if_the_solution_is_the_right_one_based_on_my_intuition', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_try_to_find_fatal_flaws_in_a_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_consider_the_potential_risks_and_consequences_associated_with_the_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_if_I_have_the_necessary_resources_skills_and_support_to_solve_the_problem_or_not', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_how_I_can_logically_and_realistically_make_the_solution_work', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_the_positive_outcomes_that_could_result_from_an_action', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_the_long_term_benefits_of_an_action', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_the_alternative_possibilities_that_could_exist_when_considering_a_decision', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_think_of_different_ways_I_could_approach_the_problem', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_try_to_think_of_an_out_of_the_box_solution', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
