# Generated by Django 2.2 on 2020-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0011_auto_20200621_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Six_hats_Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('Write_a_brief_write_up_about_how_you_effectively_used_Six_Thinking_Hats_technique_to_solve_a_problem_at_the_workplace', models.TextField()),
            ],
        ),
    ]
