# Generated by Django 2.2 on 2020-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0012_six_hats_writeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man_eff_SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('I_identify_what_and_when_to_delegate_a_task_or_role_that_will_be_motivating_for_your_employees', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_give_constructive_behavior_based_feedback', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_practise_active_listening', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_assess_conflict_situations_and_apply_the_most_appropriate_modes', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_practice_overall_team_management_and_effective_leadership_skills', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_identify_when_is_the_best_time_to_tell_vs_ask_in_a_conversation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_know_the_types_of_questions_to_use_to_dig_deeper_into_a_conversation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
            ],
        ),
    ]
