# Generated by Django 2.2 on 2020-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0013_man_eff_selfevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man_eff_RelationshipWithManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('Name_of_your_Manager', models.CharField(max_length=50)),
                ('My_manager_understands_my_problems_and_needs', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('My_manager_recognizes_my_potential', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('Regardless_of_how_much_power_he_she_has_built_into_his_her_position_my_manager_would_be_personally_inclined_to_use_his_her_power_to_help_me_solve_problems_in_my_work', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('My_supervisor_has_enough_confidence_in_me_that_he_she_would_defend_and_justify_my_decisions_if_I_were_not_present_to_do_so', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_can_count_on_my_manager_to_bail_me_out_at_his_her_expense_when_I_really_need_it', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('My_manager_has_enough_confidence_in_me_that_he_she_would_defend_and_justiy_my_decision_if_I_am_not_present_to_do_so', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_know_how_satisfied_my_manager_is_with_what_I_do', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
            ],
        ),
    ]
