# Generated by Django 2.2 on 2020-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0017_businesscommuniction_self_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation_Self_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('Before_preparing_the_content_I_make_sure_that_I_am_clear_about_the_objectives_of_the_session', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_ensure_that_all_equipment_is_functioning_properly_at_the_venue_before_starting_my_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_make_a_thorough_research_about_the_topic_and_prepare_content_that_is_interesting_and_useful', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_identify_my_audience_before_I_start_preparing_for_my_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_consider_immediate_needs_and_pain_points_and_obstacles_of_my_audience_regarding_the_topic_I_will_present', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_can_gauge_the_level_of_interest_of_my_audience_on_the_topic_being_presented', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_make_sure_that_the_contents_are_relevant_and_logical_and_meet_the_needs_of_participants', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_make_sure_that_the_content_or_information_I_am_giving_is_appropriate_to_the_culture_and_sentiments_of_the_audience', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_am_very_clear_in_the_statements_that_I_use', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_use_the_appropriate_font_size_so_that_the_on_screen_text_is_readable', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_ensure_that_the_presentation_has_a_proper_flow_clarity_and_the_right_amount_of_information', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_use_suitable_pictures_and_charts_and_figures_to_enhance_the_effectiveness_of_the_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_use_relevant_stories_and_analogies_and_examples_and_humor_etc_during_the_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_maintain_eye_contact_and_try_to_connect_with_the_participants_during_the_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_take_care_of_my_voice_modulation_and_tone_and_pitch_and_language_during_the_presentation', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
                ('I_make_sure_that_I_give_a_worthwhile_summary_and_make_a_convincing_conclusion', models.CharField(blank=True, choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=25, null=True)),
            ],
        ),
    ]
