# Generated by Django 2.2 on 2020-06-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('tepsite', '0018_presentation_self_assessment'),
    ]

    operations = [
    ]
