# Generated by Django 2.2 on 2020-06-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0019_merge_20200622_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRadioQuestions',
        ),
    ]
