# Generated by Django 2.2 on 2020-06-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0019_merge_20200622_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscommuniction_self_assessment',
            options={'verbose_name': '[Business Communication] Self Assessment Form'},
        ),
        migrations.AlterModelOptions(
            name='man_eff_employee_engagement',
            options={'verbose_name': '[Managerial Effectiveness] Employee Engagement Form'},
        ),
        migrations.AlterModelOptions(
            name='man_eff_relationshipwithmanager',
            options={'verbose_name': '[Managerial Effectiveness] Relationship with Manager Form'},
        ),
        migrations.AlterModelOptions(
            name='man_eff_selfevaluation',
            options={'verbose_name': '[Managerial Effectiveness] Self Evaluation Form'},
        ),
        migrations.AlterModelOptions(
            name='presentation_self_assessment',
            options={'verbose_name': '[Presentation Self Assessment] Self Assessment Form'},
        ),
        migrations.AlterModelOptions(
            name='six_hats_writeup',
            options={'verbose_name': '[Six Hats] Writeup'},
        ),
        migrations.AlterModelOptions(
            name='sixthinkinghats_selfevaluation',
            options={'verbose_name': '[Six Hats] Self Evaluation Form'},
        ),
        migrations.AlterModelOptions(
            name='together_win_peer_review',
            options={'verbose_name': '[Together WE WIN] Peer Review Form'},
        ),
        migrations.AlterModelOptions(
            name='together_win_self_assessment',
            options={'verbose_name': '[Together WE WIN] Self Assessment Form'},
        ),
    ]
