# Generated by Django 2.2 on 2020-06-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0020_auto_20200624_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='intern_name',
            new_name='Employee_name',
        ),
    ]
