# Generated by Django 2.2 on 2020-07-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0021_auto_20200625_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man_eff_selfevaluation',
            old_name='intern_name',
            new_name='Employee_name',
        ),
    ]
