# Generated by Django 2.2 on 2020-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0022_auto_20200701_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscommuniction_self_assessment',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='man_eff_employee_engagement',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='man_eff_relationshipwithmanager',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='presentation_self_assessment',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='together_win_peer_review',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='together_win_self_assessment',
            old_name='intern_name',
            new_name='Employee_name',
        ),
    ]
