# Generated by Django 2.2 on 2020-07-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0023_auto_20200701_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='six_hats_writeup',
            old_name='intern_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='sixthinkinghats_selfevaluation',
            old_name='intern_name',
            new_name='Employee_name',
        ),
    ]
