# Generated by Django 2.2 on 2020-07-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0024_auto_20200704_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscommuniction_self_assessment',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='man_eff_employee_engagement',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='man_eff_relationshipwithmanager',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='man_eff_selfevaluation',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='presentation_self_assessment',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='six_hats_writeup',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='sixthinkinghats_selfevaluation',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='together_win_peer_review',
            old_name='Employee_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='together_win_self_assessment',
            old_name='Employee_name',
            new_name='intern_name',
        ),
    ]
