# Generated by Django 2.2 on 2020-07-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tepsite', '0025_auto_20200704_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programfeedbackform',
            old_name='intern_name',
            new_name='employee_name',
        ),
    ]
